version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: kiname-solo-mining_app_1
      APP_PORT: 8501

  app:
    # REEMPLAZA EL HASH DE ABAJO POR EL TUYO REAL
    image: kiname01/solo-mining@sha256:17491bb93f6dcd1e54f8ee13db959d83ad1b85b4bffe71ff277037bc4db73d61
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
