version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: kiname-solo-mining_app_1
      APP_PORT: 8501

  app:
    # REEMPLAZA EL HASH DE ABAJO POR EL TUYO REAL
    image: kiname01/solo-mining:1.6.0@sha256:b6a47d3a98d4b66d57a9ff8a26a82e650b31f4cd17dafa110500797d509b931c
    ports:
      - "0.0.0.0:8557:8557" # <-- NUEVO: Expone la API REST a la red local
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
