version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: kiname-solo-mining_app_1
      APP_PORT: 8501

  app:
    
    image: kiname01/solo-mining:1.7.4@sha256:afc32be145160676bdc2b283dc914a9134374680ed61f7ee75f45c93e5e6a91e
    ports:
      - "0.0.0.0:8557:8557" # <-- NUEVO: Expone la API REST a la red local
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
